# Generated by Django 4.2.6 on 2023-10-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('in_cart', models.BooleanField(default=True)),
                ('placed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_type', models.CharField(choices=[('Thin Crust', 'Thin Crust'), ('Normal', 'Normal'), ('Cheese Burst', 'Cheese Burst')], max_length=100)),
                ('cheese_type', models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Melted Cheese', 'Melted Cheese'), ('Masaledaar Cheese', 'Masaledaar Cheese'), ('Cheese Dhamaka', 'Cheese Dhamaka')], max_length=100)),
                ('description', models.TextField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.order')),
                ('toppings', models.ManyToManyField(blank=True, null=True, to='apis.topping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
