# Generated by Django 4.2.6 on 2023-10-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_order_pizza_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.IntegerField(default=0),
        ),
        # migrations.AlterField(
        #     model_name='pizza',
        #     name='base_type',
        #     field=models.CharField(choices=[('Thin Crust', 'Thin Crust'), (100, 100), (150, 150)], max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='pizza',
        #     name='cheese_type',
        #     field=models.CharField(choices=[('Mozzarella', 'Mozzarella'), (70, 70), (100, 100), (90, 90)], max_length=100),
        # ),
    ]
