THIN_CRUST = 'Thin Crust'
NORMAL = 'Normal'
CHEESE_BURST = 'Cheese Burst'

THIN_CRUST_PRICE = 120
NORMAL_PRICE = 100
CHEESE_BURST_PRICE = 150

BASE_CHOICES = (
    (THIN_CRUST, THIN_CRUST),
    (NORMAL, NORMAL),
    (CHEESE_BURST, CHEESE_BURST)
)

BASE_CHOICES_PRICES = (
    (THIN_CRUST, 120),
    (NORMAL, 100),
    (CHEESE_BURST, 150)
)

MOZZARELLA = 'Mozzarella'
MELTED_CHEESE = 'Melted Cheese'
CHEESE_DHAMAKA = 'Cheese Dhamaka'
MASALEDAAR_CHEESE = 'Masaledaar Cheese'

MOZZARELLA_PRICE = 50
MELTED_CHEESE_PRICE_PRICE = 90
MASALEDAAR_CHEESE_PRICE = 100

CHEESE_CHOICES_PRICES = (
    (MOZZARELLA, 50),
    (MASALEDAAR_CHEESE, 100),
    (CHEESE_DHAMAKA, 90),
    (MELTED_CHEESE, 70)
)

CHEESE_CHOICES = (
    (MOZZARELLA,MOZZARELLA),
    (MELTED_CHEESE,MELTED_CHEESE),
    (MASALEDAAR_CHEESE,MASALEDAAR_CHEESE),
    (CHEESE_DHAMAKA,CHEESE_DHAMAKA)
)

PANEER = 'Paneer'
CRISPY_MUSHROOM = 'Crispy Mushroom'
JALAPENOS = 'Jalapenos'
OLIVES = 'Olives'
AVACADO = 'Avacado'
FRIED_CNION_RINGS = 'Fried Onion Rings'
SURPRISE_ME = 'Surprise Me!'


PANEER_PRICE = 50
CRISPY_MUSHROOM_PRICE = 50
JALAPENOS_PRICE = 70
OLIVES_PRICE = 70
AVACADO_PRICE = 90
FRIED_CNION_RINGS_PRICE = 50
SURPRISE_ME_PRICE = 60



TOPPING_CHOICES = (
    (PANEER, PANEER),
    (CRISPY_MUSHROOM,CRISPY_MUSHROOM),
    (JALAPENOS,JALAPENOS),
    (OLIVES,OLIVES),
    (AVACADO,AVACADO),
    (FRIED_CNION_RINGS,FRIED_CNION_RINGS),
    (SURPRISE_ME,SURPRISE_ME)
)
ACCEPTED = 'Accepted'
PREPARING = 'Preparing'
DISPATCHED = 'Dispatched'
DELIVERED = 'Delivered'

ORDER_STATUS_CHOICE = (
    (ACCEPTED, ACCEPTED),
    (PREPARING, PREPARING),
    (DISPATCHED, DISPATCHED),
    (DELIVERED, DELIVERED)
)

